use crate::market::features::FeatureVector;
use crate::market::types::{MarketId, OrderIntent, Regime, Side};

#[derive(Debug, Clone)]
pub struct MarketSnapshot {
    pub market_id: MarketId,
    pub title: String,
    pub symbol: String,
    pub window_label: String,
    pub end_label: String,
    pub side: Side,
    pub regime: Regime,
    pub score: f64,
    pub fair_value: f64,
    pub edge_buy: f64,
    pub edge_sell: f64,
    pub best_bid: f64,
    pub best_ask: f64,
    pub bid_size: f64,
    pub ask_size: f64,
    pub spread_ticks: f64,
    pub microprice: f64,
    pub trade_intensity: f64,
    pub burstiness: f64,
    pub torsion: f64,
    pub void_score: f64,
    pub wall_score: f64,
    pub expiry_secs: u64,
    pub position_qty: f64,
    pub avg_entry: f64,
    pub unrealized_pnl: f64,
    pub features: Option<FeatureVector>,
    pub intents: Vec<OrderIntent>,
    pub fair_series: Vec<(f64, f64)>,
    pub edge_series: Vec<(f64, f64)>,
    pub flow_series: Vec<(f64, f64)>,
    pub micro_series: Vec<(f64, f64)>,
}

#[derive(Debug, Clone, Default)]
pub struct WorldSnapshot {
    pub markets: Vec<MarketSnapshot>,
    pub journal_tail: Vec<String>,
    pub cash: f64,
    pub equity: f64,
    pub realized_pnl: f64,
    pub unrealized_pnl: f64,
    pub open_positions: usize,
    pub kill_switch: bool,
    pub stream_splits: u32,
    pub btc_spot: f64,
    pub signal_strength: f64,
    pub realized_pnl_5m: f64,
    pub pnl_shortfall_5m: f64,
    pub eligible_markets: usize,
    pub ticket_dollars: f64,
    pub entry_threshold: f64,
    pub exit_threshold: f64,
    pub max_spread: f64,
    pub paper_real_mode: bool,
}
